version: '3.6'

services: 

  mysql:
    image: mysql
    container_name: go-mysql
    restart: always
    ports: 
      - 3306:3306
    environment: 
        MYQSL_ROOT_HOST: localhost
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: mydb
    networks:
      - webapp_net      
    volumes: 
    - .mysql-data:/var/lib/mysql:rw

  web:
    container_name: go-web
    image: web_app:latest
    build:
        context: ./
        dockerfile: Dockerfile.dev
    volumes:
      - ./bin/go-boilerplate:/go-boilerplate
      - ./config:/config
      - ./migrations:/migrations
    ports: 
      - "1200:1200"      
    networks:
      - webapp_net
    environment:
      - WAIT_HOSTS=go-mysql:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30 
      - ENV_NAME=local 
    command: sh -c "ls && /wait && /go-boilerplate"  
    depends_on: 
      - mysql    

networks: 
  webapp_net:
    external: 
      name: go-net
