version: '3.6'

services: 

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    ports: 
      - 3308:3308
    environment: 
        MYSQL_ROOT_HOST: localhost
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: mydb
        MYSQL_USER: user
        MYSQL_PASSWORD: user
    networks:
      - webapp_net      
    volumes: 
    - data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports: 
      - 8080:8080
    networks:
      - webapp_net   
  web:
    container_name: web_app
    image: web_app:latest
    build: ./
    volumes:
      - ./bin/:/web_app/
    ports: 
      - "1200:1200"      
    networks:
      - webapp_net
    environment:
      - WAIT_HOSTS=mysql:3308
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30  
volumes: 
  data:
networks: 
  webapp_net:
    driver: bridge