// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"go-boilerplate/src/http_app"
	"go-boilerplate/src/service/class_service"
	"go-boilerplate/src/storage"
)

// Injectors from wire.go:

func InitilizeAppRequirements(config storage.DbConfig) *http_app.App {
	db := storage.NewDB(config)
	classesRepo := storage.NewClassesRepo(db)
	classService := class_service.NewClassService(classesRepo)
	app := http_app.Initialize(classService)
	return app
}
